FROM nginx:1.21.1
COPY www/index.html /opt/www/

#COPY nginx.conf /etc/nginx/nginx.conf
#COPY ./certs/nginx-selfsigned.crt /etc/ssl/certs/nginx-selfsigned.crt
#COPY ./certs/nginx-selfsigned.key /etc/ssl/private/nginx-selfsigned.key
